### PR TITLE
Address a number of issues

### PR DESCRIPTION
**Pull request by JJ**
Without touching the code, address some metadata issues, including some CPANTs problems. 
I don't know if changing the command line will have an impact on the `Code::TidyAll::Plugin::JSBeautifier` module, because it's calling the script with options. Best check it and/or include it as part of the tests (if it's not already)

### CODE REVIEW

**Comment by fayland** [comment]
what's your PAUSE id? we can make you the co-maintainer so that you can do a release to PAUSE?

Thanks

**Comment by JJ** [comment]
It's JMERELO. Thanks, it will be an honor :-)

**Comment by fayland** [comment]
Added JMERELO to co-maintainers of JavaScript::Beautifier.

thanks for all the help. I also made you PUSH permission on this repos. you can merge your PR directly if needed. 

Thanks

**Comment by JJ** [comment]
Will do... although for the time being I'll focus on the Perl6 GitHub one.
I need that for my TPF grant. Thanks!

**Pull request merged**
